### ISSUE TITLE
Can't control cursor

### ISSUE THREAD

**Issue by cevn** [gchp/rustbox#21]
This is a bit of an odd issue. I cannot control the appearance of the cursor on only one my computers, running OSX Mavericks. On the other one, with Yosemite, I can use rustbox.set_cursor() to control its position, but it has no effect on this one. 

I'll attach a picture of what it looks like and what it should look like. Here the cursor is following the input for some reason. 

![screen shot 2015-02-01 at 7 48 55 pm](https://cloud.githubusercontent.com/assets/4663020/5994694/6b9e4020-aa4b-11e4-9381-e4c68372e636.png)

Here it seems to work as expected. There is no difference in code on the two boxes. 
![screen shot 2015-02-01 at 7 51 00 pm](https://cloud.githubusercontent.com/assets/4663020/5994701/ca3c73fe-aa4b-11e4-8f84-28b0aa3fd4d7.png)

**Comment by gchp** [comment]
Hmm, so its only happening on Mavericks? Do you have the code that generated this example?

**Comment by cevn** [comment]
I added you to the repository, try cloning it and `cargo run` - it's nothing sensitive.

**Comment by gchp** [comment]
Ok, had a look and nothing obvious is standing out to me. Can you give some more info on your setup?

- value of your TERM env variable
- terminal emulator

Also, it might be worth trying the [termbox examples](https://github.com/nsf/termbox) (instructions in the README there). I don't know if this is a rustbox issue, or if termbox itself is causing the problem.

**Comment by cevn** [comment]
```
$[~] echo $TERM
xterm-color
```

terminal emulator in use is iTerm2. I'll give  the termbox examples a try and if they display the same behavior I'll close this issue

**Comment by gchp** [comment]
Try `export TERM=xterm-256color` and run your project again. I wonder if its just some strange terminal specific behaviour.

**Comment by cevn** [comment]
Actually, that fixed it haha. Good call...

**Comment by gchp** [comment]
Sweet! If you run into other issues, let me know!
