### ISSUE TITLE
Shift+Tab capability

### ISSUE THREAD

**Issue by freiguy1** [gchp/rustbox#25]
Hello.  I am working on a project where the tab button navigates from control to control (defined as text boxes, and list selects).  I'd like to implement shift+tab to do the opposite, like it works in browsers and most other graphical applications.  However, the last time I attempted capturing shift+tab, it made it seem like 3 buttons were being pressed in sequence. None of them being shift or tab.  Is this possible, or not really?

**Comment by gchp** [comment]
@freiguy1 sorry for the delay, somehow I missed this issue. 

It seems like you can't do this. It's a limitation of termbox itself. In the termbox repo there is a demo called keyboard.c which when compiled and run will show you what termbox sees when you press certain keys. Its very useful for seeing what key combinations you can use.

Here's the link: https://github.com/nsf/termbox/tree/master/src/demo

You'll need to install termbox, then build the `keyboard.c` file with `cc keyboard.c -ltermbox -o keyboard` and run with `./keyboard`.

If you run into other problems, let me know!
