### ISSUE TITLE
Can't compile with rustc beta 1.1

### ISSUE THREAD

**Issue by benekastah** [gchp/rustbox#36]
Exact version: `rustc 1.1.0-beta (cd7d89af9 2015-05-16) (built 2015-05-16)`

```
   Compiling rustbox v0.6.1
/Users/benekastah/.cargo/registry/src/github.com-1ecc6299db9ec823/rustbox-0.6.1/src/rustbox.rs:1:1: 1:18 error: unstable feature
/Users/benekastah/.cargo/registry/src/github.com-1ecc6299db9ec823/rustbox-0.6.1/src/rustbox.rs:1 #![feature(libc)]
                                                                                                 ^~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
/Users/benekastah/.cargo/registry/src/github.com-1ecc6299db9ec823/rustbox-0.6.1/src/rustbox.rs:2:1: 2:34 error: unstable feature
/Users/benekastah/.cargo/registry/src/github.com-1ecc6299db9ec823/rustbox-0.6.1/src/rustbox.rs:2 #![feature(optin_builtin_traits)]
                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to 2 previous errors
Could not compile `rustbox`.
```

I also can't compile with the rustc 1.0 since tempfile (a dependency of a dependency I guess) won't compile on that version.

**Comment by nihakue** [comment]
Having the same problem. I think it might work with the nightly build?

**Comment by gchp** [comment]
Yeah unfortunately it has to be the nightly builds for now.

I've been meaning to spend some time getting it to build on the stable channel, using cargo features. But I just haven't had the time to sit down and get it fixed. So yeah, for now you need to be on the beta channel. Sorry about that!

**Comment by Yamakaky** [comment]
Same thing on rust 1.1.

**Comment by neuschaefer** [comment]
@benekastah It should work now; does it for you?

**Comment by droundy** [comment]
It does work for me on 1.2 stable, so I imagine you can close this now.

**Comment by gchp** [comment]
Agreed!
