### ISSUE TITLE
Unable to compile example on Mac OSX

### ISSUE THREAD

**Issue by nihakue** [gchp/rustbox#37]
/Users/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/tempfile-0.4.0/src/imp/unix.rs:45:17:     45:21 error: unresolved name `path`. Did you mean `dir`?
    /Users/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/tempfile-0.4.0/src/imp/unix.rs:45          create_unix(path)
                                                                                                                 ^~~~
    error: aborting due to previous error
    Build failed, waiting for other jobs to finish...
    Could not compile `tempfile`.

I'm not actually aware if this is supposed to work right now or not. This error was generated with:

    cargo run --example hello-world

**Comment by gchp** [comment]
Hey!
Try run `cargo update` then run the example again and see what happens. There's a newer version of `tempfile` out that will get pulled down when you run `cargo update`. Let me know how that goes!

**Comment by nihakue** [comment]
Hmm, same error using tempfile v0.5.0

    Nadecinogut:rustbox gabriel$ cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Nadecinogut:rustbox gabriel$ cargo run --example hello-world
    Compiling tempfile v0.5.0
    /Users/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/tempfile-0.5.0/src/imp/unix.rs:45:17:     45:21 error: unresolved name `path`. Did you mean `dir`?
    /Users/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/tempfile-0.5.0/src/imp/unix.rs:45         create_unix(path)
                                                                                                                 ^~~~
    error: aborting due to previous error
    Could not compile `tempfile`.

**Comment by nihakue** [comment]
Looking at the 0.5.0 source code for tempfile, it does just seam like a typo. 

    #[inline(always)]
    #[cfg(not(target_os = "linux"))]
    pub fn create(dir: &Path) -> io::Result<File> {
        create_unix(path)
    }

**Comment by gchp** [comment]
Tempfile `0.5.1` has been released. Run `cargo update` again then try run the example. Works for me now so I'll close the issue. If you still have problems, feel free to re-open!
