### ISSUE TITLE
remove Option from KeyEvent

### ISSUE THREAD

**Issue by benaryorg** [gchp/rustbox#51]
I just wrote a small event-loop and noticed the `Some` I needed to place everywhere.

After a while it gets a little annoying.
So I'm suggesting the following change:
- [`KeyEvent`](https://github.com/gchp/rustbox/blob/0.7.2/src/rustbox.rs#L33) will be `KeyEvent(Key)`
- [`Key` enum](https://github.com/gchp/rustbox/blob/0.7.2/src/keyboard.rs#L2) will contain something like an `Unhandled` or `Other` element wrapping an `u16`
- ~~[`Key::from_code(u16)`](https://github.com/gchp/rustbox/blob/0.7.2/src/keyboard.rs#L25) will not return an `Option` but a `Key` and in the `_` branch returns `Key::Unhandled(code)`~~
    - Sorry I did not understand what the function is for

The functionality stays the same but solved more "rust-like" as we can use more beautiful match-branches.

**Edit:** If you are okay with the proposed changes I would like to send this as a PR to make your life a bit easier.

**Comment by benaryorg** [comment]
I made the changes to [my fork](https://github.com/benaryorg/rustbox/), if you want to have a look.

I if you want to merge it, just say so, I'll send a PR (the version bump would then be up to you).

**Comment by gchp** [comment]
@benaryorg sorry for the super long delay on getting back to you here.

A PR for this would be welcomed! Thank you for taking the time on it.
