### ISSUE TITLE
No alt key.

### ISSUE THREAD

**Issue by Ticki** [gchp/rustbox#54]

**Comment by gchp** [comment]
Hello.

See this this comment for why there is no alt key be default: https://github.com/nsf/termbox/issues/44#issuecomment-67156091

Rustbox is a wrapper of the termbox library, so we are limited to the functionality it provides.

If you want to use the ALT key, you need to initialize Rustbox with the `InputMode::Alt` option.

**Comment by Ticki** [comment]
Thanks!

**Comment by dpc** [comment]
Handling Alt is usually done by checking if `ESC` was followed by something. if it was not immediately followed, it was `Esc` keypressed. If it was - it was an `Alt` sequence. I don't really see a reason why this couldn't be handled directly.

Also, in `Alt` mode termbox sets alt modifier: https://github.com/nsf/termbox/blob/0178b0123e176b9c4656177c07af832bc141b03f/src/input.inl#L192, while `rustbox` seems to just ignore it.
