### ISSUE TITLE
Does there any updates for pure rust box?

### ISSUE THREAD

**Issue by lucasjinreal** [gchp/rustbox#88]
Hi, does there any updates for implementing pure rustbox?

**Comment by gchp** [comment]
I had started a branch which got most things working but I never pushed it. It was pretty basic and didn't cover all terminal types and hadn't gotten to the Windows support. I'll see if I can find the branch and push it up here.

**Comment by gchp** [comment]
Update: just pushed the [`rewrite`](https://github.com/gchp/rustbox/tree/rewrite) branch.

There is an example called `basic.rs` which shows where it is at functionality wise. Still a ways to go. I still hope to finish it, just not had time recently.

**Comment by lucasjinreal** [comment]
@gchp  Thanks u so much! I am using rustbox for an external dependencies in my project. So hope there would be pure rust implementation of this. However, using as a c wrapper also works fine. Hoping this crate can stay stable.
